/*
    LibrePods - AirPods liberated from Apple's ecosystem
    Copyright (C) 2025 LibrePods contributors

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.
*/

package me.kavishdevar.librepods.diagnostics

/**
 * Correlation identifiers are generated by the routing state machine. AACP responses do not
 * carry a request identifier, so [takeoverAttemptId] only represents temporal correlation.
 */
data class RoutingCorrelation(
    val playbackCycleId: String? = null,
    val takeoverAttemptId: String? = null,
    val aacpSessionId: String? = null,
    val causeSequence: Long? = null,
)

enum class RoutingSeverity {
    DEBUG,
    INFO,
    WARNING,
    ERROR,
}

enum class RoutingStopReason {
    USER,
    SERVICE_STOPPED,
    PROCESS_RESTARTED,
    INTERNAL_ERROR,
}

enum class RoutingAction {
    AUTOMATIC_TAKEOVER,
    MANUAL_TAKEOVER,
    RELEASE_OWNERSHIP,
    HOST_STREAMING_STATE,
    MEDIA_KEY_PLAY,
    MEDIA_KEY_PAUSE,
    AACP_CONTROL_REFRESH,
    PHONE_SPEAKER_POLICY,
    A2DP_CONNECT,
}

enum class AacpOperation {
    OWNERSHIP,
    MEDIA_INFORMATION,
    HIJACK_REQUEST,
    HIJACK_REVERSED,
    SHOW_NEARBY_UI,
    HANDSHAKE,
    NOTIFICATION_REQUEST,
    CONTROL_SESSION_REFRESH,
    OTHER_ROUTING,
}

enum class AacpSendOutcome {
    SENT,
    SKIPPED,
    VALIDATION_FAILED,
    SOCKET_UNAVAILABLE,
    WRITE_FAILED,
}

enum class AacpStateKind {
    REQUESTED_OWNERSHIP,
    CONFIRMED_OWNERSHIP,
    AUDIO_SOURCE,
    REMOTE_STREAMING,
    SOCKET,
}

enum class DebounceEvent {
    SCHEDULED,
    CANCELLED,
    FIRED,
    STALE,
}

data class PlaybackConfigurationTrace(
    val usage: Int,
    val usageName: String,
    val contentType: Int,
    val contentTypeName: String,
    val outputDeviceType: Int? = null,
    val outputDeviceTypeName: String? = null,
    val targetDeviceMatched: Boolean? = null,
    val playerState: Int? = null,
    val playerStateName: String? = null,
    val policyEnabled: Boolean,
    val eligible: Boolean,
    val reason: String,
)

/**
 * The permitted event payloads are deliberately semantic. There is no raw packet, hexadecimal
 * payload, MAC address, serial number, media title, notification content, or cryptographic-key
 * event type.
 */
sealed interface RoutingEventDetail {
    val eventName: String

    data class PlaybackSnapshot(
        val observationSource: String,
        val configurations: List<PlaybackConfigurationTrace>,
        val configurationCount: Int,
        val eligibleConfigurationCount: Int,
        val eligiblePlaybackActive: Boolean,
        val eligiblePlaybackRoutedToTarget: Boolean,
    ) : RoutingEventDetail {
        override val eventName = "playback_snapshot"
    }

    data class Debounce(
        val event: DebounceEvent,
        val delayMs: Long,
        val generation: Long,
        val reason: String,
    ) : RoutingEventDetail {
        override val eventName = "debounce"
    }

    data class Decision(
        val action: RoutingAction,
        val allowed: Boolean,
        val reason: String,
        val gates: Map<String, Boolean> = emptyMap(),
    ) : RoutingEventDetail {
        override val eventName = "routing_decision"
    }

    data class StateTransition(
        val stateMachine: String,
        val previousState: String,
        val newState: String,
        val trigger: String,
        val reason: String,
    ) : RoutingEventDetail {
        override val eventName = "routing_state_transition"
    }

    data class A2dpStateChanged(
        val signal: String,
        val previousState: String?,
        val newState: String,
        val targetDeviceMatched: Boolean,
        val observationSource: String,
    ) : RoutingEventDetail {
        override val eventName = "a2dp_state_changed"
    }

    data class AacpSend(
        val operation: AacpOperation,
        val outcome: AacpSendOutcome,
        val socketConnected: Boolean,
        val requestedValue: Int? = null,
        val reason: String,
    ) : RoutingEventDetail {
        override val eventName = "aacp_send"
    }

    data class AacpStateChanged(
        val kind: AacpStateKind,
        val previousValue: String?,
        val newValue: String,
        val sourceAlias: String? = null,
        val sourceType: String? = null,
        val correlationBasis: String? = null,
    ) : RoutingEventDetail {
        override val eventName = "aacp_state_changed"
    }

    data class PhoneSoundPolicy(
        val enabled: Boolean,
        val targetAvailable: Boolean,
        val requestedUsages: Set<Int>,
        val status: String,
        val permissionGranted: Boolean,
        val reason: String,
    ) : RoutingEventDetail {
        override val eventName = "phone_sound_policy"
    }

    data class SettingsSnapshot(
        val revision: Long,
        val automaticTakeoverEnabled: Boolean,
        val mediaTakeoverEnabled: Boolean,
        val enabledUsages: Set<Int>,
        val debounceMs: Long,
        val additionalFlags: Map<String, Boolean> = emptyMap(),
    ) : RoutingEventDetail {
        override val eventName = "settings_snapshot"
    }

    data class SettingsChanged(
        val revision: Long,
        val setting: String,
        val previousValue: String,
        val newValue: String,
    ) : RoutingEventDetail {
        override val eventName = "settings_changed"
    }

    data class ActionResult(
        val action: RoutingAction,
        val outcome: String,
        val reason: String,
    ) : RoutingEventDetail {
        override val eventName = "routing_action_result"
    }

    data class Error(
        val component: String,
        val code: String,
        val exceptionType: String? = null,
        val message: String? = null,
        val stackTrace: List<String> = emptyList(),
    ) : RoutingEventDetail {
        override val eventName = "error"
    }

    data class Marker(
        val label: String,
    ) : RoutingEventDetail {
        override val eventName = "marker"
    }

    data class SessionStarted(
        val appVersion: String,
        val versionCode: Int,
        val buildType: String,
        val flavor: String,
        val manufacturer: String,
        val model: String,
        val androidRelease: String,
        val apiLevel: Int,
    ) : RoutingEventDetail {
        override val eventName = "session_started"
    }

    data class SessionStopped(
        val reason: RoutingStopReason,
        val droppedEventCount: Long,
    ) : RoutingEventDetail {
        override val eventName = "session_stopped"
    }

    data class DroppedEvents(
        val count: Long,
    ) : RoutingEventDetail {
        override val eventName = "dropped_events"
    }
}

data class RoutingEvent(
    val schemaVersion: Int = ROUTING_TRACE_SCHEMA_VERSION,
    val sessionId: String,
    val sequence: Long,
    val wallTimeEpochMs: Long,
    val elapsedRealtimeNanos: Long,
    val severity: RoutingSeverity,
    val correlation: RoutingCorrelation,
    val detail: RoutingEventDetail,
)

const val ROUTING_TRACE_SCHEMA_VERSION = 2
